//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBypass.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestBypass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] IV {
            get {
                object obj = ResourceManager.GetObject("IV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.16.0.0
        ///10.16.0.1
        ///10.16.0.2
        ///10.16.0.3
        ///10.16.0.4
        ///10.16.0.5
        ///10.16.0.6
        ///10.16.0.7
        ///10.16.0.8
        ///10.16.0.9
        ///10.16.0.10
        ///10.16.0.11
        ///10.16.0.12
        ///10.16.0.13
        ///10.16.0.14
        ///10.16.0.15
        ///10.16.0.16
        ///10.16.0.17
        ///10.16.0.18
        ///10.16.0.19
        ///10.16.0.20
        ///10.16.0.21
        ///10.16.0.22
        ///10.16.0.23
        ///10.16.0.24
        ///10.16.0.25
        ///10.16.0.26
        ///10.16.0.27
        ///10.16.0.28
        ///10.16.0.29
        ///10.16.0.30
        ///10.16.0.31
        ///10.16.0.32
        ///10.16.0.33
        ///10.16.0.34
        ///10.16.0.35
        ///10.16.0.36
        ///10.16.0.37
        ///10.16.0.38
        ///10.16.0.39
        ///10.16.0.40
        ///10.16.0.41
        ///10.16.0.42
        ///10.16. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PC {
            get {
                return ResourceManager.GetString("PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SHound {
            get {
                object obj = ResourceManager.GetObject("SHound", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
